/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiEngineRouteImport } from './routes/api/engine'
import { Route as ApiAiDecideRouteImport } from './routes/api/ai/decide'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiIndodaxOhlcRouteImport } from './routes/api/indodax/ohlc'
import { Route as ApiIndodaxPairsRouteImport } from './routes/api/indodax/pairs'
import { Route as ApiIndodaxPrivateRouteImport } from './routes/api/indodax/private'
import { Route as ApiIndodaxTickersRouteImport } from './routes/api/indodax/tickers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEngineRoute = ApiEngineRouteImport.update({
  id: '/api/engine',
  path: '/api/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiDecideRoute = ApiAiDecideRouteImport.update({
  id: '/api/ai/decide',
  path: '/api/ai/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndodaxOhlcRoute = ApiIndodaxOhlcRouteImport.update({
  id: '/api/indodax/ohlc',
  path: '/api/indodax/ohlc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndodaxPairsRoute = ApiIndodaxPairsRouteImport.update({
  id: '/api/indodax/pairs',
  path: '/api/indodax/pairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndodaxPrivateRoute = ApiIndodaxPrivateRouteImport.update({
  id: '/api/indodax/private',
  path: '/api/indodax/private',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndodaxTickersRoute = ApiIndodaxTickersRouteImport.update({
  id: '/api/indodax/tickers',
  path: '/api/indodax/tickers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/engine': typeof ApiEngineRoute
  '/api/ai/decide': typeof ApiAiDecideRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/indodax/ohlc': typeof ApiIndodaxOhlcRoute
  '/api/indodax/pairs': typeof ApiIndodaxPairsRoute
  '/api/indodax/private': typeof ApiIndodaxPrivateRoute
  '/api/indodax/tickers': typeof ApiIndodaxTickersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/engine': typeof ApiEngineRoute
  '/api/ai/decide': typeof ApiAiDecideRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/indodax/ohlc': typeof ApiIndodaxOhlcRoute
  '/api/indodax/pairs': typeof ApiIndodaxPairsRoute
  '/api/indodax/private': typeof ApiIndodaxPrivateRoute
  '/api/indodax/tickers': typeof ApiIndodaxTickersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/engine': typeof ApiEngineRoute
  '/api/ai/decide': typeof ApiAiDecideRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/indodax/ohlc': typeof ApiIndodaxOhlcRoute
  '/api/indodax/pairs': typeof ApiIndodaxPairsRoute
  '/api/indodax/private': typeof ApiIndodaxPrivateRoute
  '/api/indodax/tickers': typeof ApiIndodaxTickersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/engine'
    | '/api/ai/decide'
    | '/api/auth/$'
    | '/api/indodax/ohlc'
    | '/api/indodax/pairs'
    | '/api/indodax/private'
    | '/api/indodax/tickers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/engine'
    | '/api/ai/decide'
    | '/api/auth/$'
    | '/api/indodax/ohlc'
    | '/api/indodax/pairs'
    | '/api/indodax/private'
    | '/api/indodax/tickers'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/engine'
    | '/api/ai/decide'
    | '/api/auth/$'
    | '/api/indodax/ohlc'
    | '/api/indodax/pairs'
    | '/api/indodax/private'
    | '/api/indodax/tickers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiEngineRoute: typeof ApiEngineRoute
  ApiAiDecideRoute: typeof ApiAiDecideRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiIndodaxOhlcRoute: typeof ApiIndodaxOhlcRoute
  ApiIndodaxPairsRoute: typeof ApiIndodaxPairsRoute
  ApiIndodaxPrivateRoute: typeof ApiIndodaxPrivateRoute
  ApiIndodaxTickersRoute: typeof ApiIndodaxTickersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engine': {
      id: '/api/engine'
      path: '/api/engine'
      fullPath: '/api/engine'
      preLoaderRoute: typeof ApiEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/decide': {
      id: '/api/ai/decide'
      path: '/api/ai/decide'
      fullPath: '/api/ai/decide'
      preLoaderRoute: typeof ApiAiDecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/indodax/ohlc': {
      id: '/api/indodax/ohlc'
      path: '/api/indodax/ohlc'
      fullPath: '/api/indodax/ohlc'
      preLoaderRoute: typeof ApiIndodaxOhlcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/indodax/pairs': {
      id: '/api/indodax/pairs'
      path: '/api/indodax/pairs'
      fullPath: '/api/indodax/pairs'
      preLoaderRoute: typeof ApiIndodaxPairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/indodax/private': {
      id: '/api/indodax/private'
      path: '/api/indodax/private'
      fullPath: '/api/indodax/private'
      preLoaderRoute: typeof ApiIndodaxPrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/indodax/tickers': {
      id: '/api/indodax/tickers'
      path: '/api/indodax/tickers'
      fullPath: '/api/indodax/tickers'
      preLoaderRoute: typeof ApiIndodaxTickersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiEngineRoute: ApiEngineRoute,
  ApiAiDecideRoute: ApiAiDecideRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiIndodaxOhlcRoute: ApiIndodaxOhlcRoute,
  ApiIndodaxPairsRoute: ApiIndodaxPairsRoute,
  ApiIndodaxPrivateRoute: ApiIndodaxPrivateRoute,
  ApiIndodaxTickersRoute: ApiIndodaxTickersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
